//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Photo_Album.Models
{
    public partial class Photo
    {
        public int id { get; set; }
        public string name { get; set; }
        public string filename { get; set; }
        public string caption { get; set; }
        public string photographer { get; set; }
        public string license { get; set; }
        public string album { get; set; }
    }
    
}
